### ISSUE TITLE
Error handling for decryption…

### ISSUE THREAD

**Issue by KopfKrieg** [KopfKrieg/cloudzec#16]
```
Decrypt file: phUW6Q0tAMtJ0ciapXCehnE9Q4o3MJew
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/gnupg/_meta.py", line 624, in _read_response
    result._handle_status(keyword, value)
  File "/usr/lib/python3.4/site-packages/gnupg/_parsers.py", line 1506, in _handle_status
    super(Crypt, self)._handle_status(key, value)
  File "/usr/lib/python3.4/site-packages/gnupg/_parsers.py", line 1419, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'FAILURE'

phUW6Q0tAMtJ0ciapXCehnE9Q4o3MJew → test
´´´
File is overwritten, resulting in an empty file

Edit: Only happens with python-gnupg-isis on Arch Linux, with python-gnupg everything is fine. Seems like a problem of python-gnupg-isis

**Comment by KopfKrieg** [comment]
Seems like an issue in python-gnupg(-ng), closing.
